using Sasd.Numerics.Common;
using Sasd.Numerics.LinearAlgebra;

namespace Sasd.Numerics.Approximation;

/// <summary>
/// Least-squares approximation helpers implemented with small, transparent reference algorithms.
/// </summary>
/// <remarks>
/// <para>
/// General linear fits prefer Householder QR for square/tall full-column-rank design matrices.
/// QR avoids explicitly forming the normal equations <c>A^T*A</c> and therefore avoids squaring
/// the condition number as the historical reference implementation did.
/// </para>
/// <para>
/// Rank-deficient and underdetermined general-basis fits fall back to the singular value
/// decomposition and therefore return a tolerance-aware minimum-norm solution instead of failing
/// solely because the design matrix lacks full column rank.
/// </para>
/// </remarks>
public static partial class LeastSquares
{
    /// <summary>Fits a polynomial <c>c0 + c1*x + ... + cn*x^n</c> in the least-squares sense.</summary>
    /// <remarks>
    /// Polynomial basis values are generated by recurrence (<c>1, x, x^2, ...</c>) rather than
    /// creating delegates and repeatedly calling <see cref="System.Math.Pow(double, double)"/>.
    /// A polynomial fit still requires at least <c>degree + 1</c> observations; this keeps the
    /// convenience API away from surprising underdetermined coefficient choices. The completed
    /// full-rank design is solved with Householder QR, with SVD available as a defensive fallback
    /// if the sampled polynomial basis is numerically rank deficient.
    /// </remarks>
    public static double[] FitPolynomial(IReadOnlyList<double> x, IReadOnlyList<double> y, int degree)
    {
        if (degree < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(degree));
        }

        NumericGuard.SameLength(x, y, nameof(x), nameof(y));
        if (x.Count == 0)
        {
            throw new ArgumentException("At least one data point is required.", nameof(x));
        }

        var basisCountLong = (long)degree + 1;
        if (basisCountLong > x.Count)
        {
            throw new ArgumentException("Number of data points must be at least degree + 1.", nameof(degree));
        }

        var basisCount = (int)basisCountLong;
        var design = new DenseMatrix(x.Count, basisCount);

        for (var sample = 0; sample < x.Count; sample++)
        {
            EnsureFiniteSample(x[sample], y[sample], sample);
            var row = design.GetMutableRowSpan(sample);
            var power = 1.0;
            for (var basis = 0; basis < basisCount; basis++)
            {
                row[basis] = power;
                if (basis + 1 < basisCount)
                {
                    power *= x[sample];
                    if (!double.IsFinite(power))
                    {
                        throw new ArithmeticException("Polynomial basis generation produced a non-finite value.");
                    }
                }
            }
        }

        return SolveModernLeastSquares(design, y);
    }

    /// <summary>Fits a model that is linear in the supplied basis functions.</summary>
    /// <remarks>
    /// <para>
    /// Each basis function is evaluated exactly once for each sample and cached in a compact
    /// row-major design matrix. Besides reducing callback overhead, this gives deterministic
    /// semantics for expensive basis functions.
    /// </para>
    /// <para>
    /// Full-column-rank square/tall designs use Householder QR. Rank-deficient or underdetermined
    /// designs use the SVD and return its tolerance-aware minimum-norm solution. This makes the
    /// general basis API suitable for modern regression building blocks without changing the
    /// simpler polynomial convenience contract.
    /// </para>
    /// </remarks>
    public static double[] FitBasis(
        IReadOnlyList<double> x,
        IReadOnlyList<double> y,
        IReadOnlyList<Func<double, double>> basisFunctions)
    {
        NumericGuard.SameLength(x, y, nameof(x), nameof(y));
        ArgumentNullException.ThrowIfNull(basisFunctions);
        if (x.Count == 0)
        {
            throw new ArgumentException("At least one data point is required.", nameof(x));
        }

        if (basisFunctions.Count == 0)
        {
            throw new ArgumentException("At least one basis function is required.", nameof(basisFunctions));
        }

        var bases = new Func<double, double>[basisFunctions.Count];
        for (var basis = 0; basis < bases.Length; basis++)
        {
            bases[basis] = basisFunctions[basis]
                ?? throw new ArgumentException("Basis functions must not contain null entries.", nameof(basisFunctions));
        }

        var design = new DenseMatrix(x.Count, bases.Length);
        for (var sample = 0; sample < x.Count; sample++)
        {
            var xValue = x[sample];
            EnsureFiniteSample(xValue, y[sample], sample);
            var row = design.GetMutableRowSpan(sample);
            for (var basis = 0; basis < bases.Length; basis++)
            {
                row[basis] = EvaluateBasis(bases[basis], xValue);
            }
        }

        return SolveModernLeastSquares(design, y);
    }

    /// <summary>Evaluates polynomial coefficients ordered from constant term to highest degree.</summary>
    public static double EvaluatePolynomial(IReadOnlyList<double> coefficients, double x)
    {
        ArgumentNullException.ThrowIfNull(coefficients);
        NumericGuard.Finite(x, nameof(x));

        var result = 0.0;
        for (var i = coefficients.Count - 1; i >= 0; i--)
        {
            var coefficient = coefficients[i];
            if (!double.IsFinite(coefficient))
            {
                throw new ArgumentOutOfRangeException(nameof(coefficients), "Polynomial coefficients must be finite.");
            }

            result = (result * x) + coefficient;
        }

        if (!double.IsFinite(result))
        {
            throw new ArithmeticException("Polynomial evaluation produced a non-finite value.");
        }

        return result;
    }

    private static double[] SolveModernLeastSquares(DenseMatrix design, IReadOnlyList<double> y)
    {
        // QR remains the preferred path when it applies: it is cheaper than a complete SVD and
        // already gives a robust full-rank least-squares solution without normal equations.
        if (design.Rows >= design.Columns)
        {
            var qr = QrFactorization.Decompose(design);
            if (qr.IsFullColumnRank)
            {
                return qr.SolveLeastSquares(y);
            }
        }

        // SVD is the principled fallback for rank deficiency and wide/underdetermined designs.
        // It also keeps the rank threshold and minimum-norm semantics explicit and reusable.
        var svd = SingularValueDecomposition.Decompose(design);
        return svd.SolveLeastSquares(y);
    }

    private static double EvaluateBasis(Func<double, double> basis, double x)
    {
        var value = basis(x);
        if (!double.IsFinite(value))
        {
            throw new ArithmeticException("A least-squares basis function returned a non-finite value.");
        }

        return value;
    }

    private static void EnsureFiniteSample(double x, double y, int sampleIndex)
    {
        if (!double.IsFinite(x) || !double.IsFinite(y))
        {
            throw new ArgumentOutOfRangeException(
                nameof(x),
                $"Least-squares sample {sampleIndex} contains a non-finite x or y value.");
        }
    }
}
