using Sasd.Numerics.Common;
using Sasd.Numerics.LinearAlgebra;

namespace Sasd.Numerics.Approximation;

/// <summary>
/// Least-squares approximation helpers implemented with small, transparent reference algorithms.
/// </summary>
/// <remarks>
/// General linear fits use normal equations with partial pivoting. V1 keeps that dependency-free
/// formulation, but caches the design matrix so basis callbacks are evaluated only once per sample.
/// For severely ill-conditioned problems a later QR/SVD backend remains the preferred evolution.
/// </remarks>
public static partial class LeastSquares
{
    /// <summary>Fits a polynomial <c>c0 + c1*x + ... + cn*x^n</c> in the least-squares sense.</summary>
    /// <remarks>
    /// Polynomial basis values are generated by recurrence (<c>1, x, x^2, ...</c>) rather than
    /// creating delegates and repeatedly calling <see cref="System.Math.Pow(double, double)"/>.
    /// </remarks>
    public static double[] FitPolynomial(IReadOnlyList<double> x, IReadOnlyList<double> y, int degree)
    {
        if (degree < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(degree));
        }

        NumericGuard.SameLength(x, y, nameof(x), nameof(y));
        if (x.Count == 0)
        {
            throw new ArgumentException("At least one data point is required.", nameof(x));
        }

        var basisCountLong = (long)degree + 1;
        if (basisCountLong > x.Count)
        {
            throw new ArgumentException("Number of data points must be at least degree + 1.", nameof(degree));
        }

        var basisCount = (int)basisCountLong;
        var design = AllocateDesignMatrix(x.Count, basisCount);

        for (var sample = 0; sample < x.Count; sample++)
        {
            EnsureFiniteSample(x[sample], y[sample], sample);
            var offset = sample * basisCount;
            var power = 1.0;
            for (var basis = 0; basis < basisCount; basis++)
            {
                design[offset + basis] = power;
                if (basis + 1 < basisCount)
                {
                    power *= x[sample];
                    if (!double.IsFinite(power))
                    {
                        throw new ArithmeticException("Polynomial basis generation produced a non-finite value.");
                    }
                }
            }
        }

        return SolveNormalEquations(design, y, x.Count, basisCount);
    }

    /// <summary>Fits a model that is linear in the supplied basis functions.</summary>
    /// <remarks>
    /// Each basis function is evaluated exactly once for each sample and cached in a compact
    /// row-major design matrix. Besides reducing callback overhead, this gives deterministic
    /// semantics for expensive basis functions and avoids the old O(samples*basis^2) evaluations.
    /// Basis callbacks should therefore be pure functions of their argument.
    /// </remarks>
    public static double[] FitBasis(
        IReadOnlyList<double> x,
        IReadOnlyList<double> y,
        IReadOnlyList<Func<double, double>> basisFunctions)
    {
        NumericGuard.SameLength(x, y, nameof(x), nameof(y));
        ArgumentNullException.ThrowIfNull(basisFunctions);
        if (x.Count == 0)
        {
            throw new ArgumentException("At least one data point is required.", nameof(x));
        }

        if (basisFunctions.Count == 0)
        {
            throw new ArgumentException("At least one basis function is required.", nameof(basisFunctions));
        }

        if (x.Count < basisFunctions.Count)
        {
            throw new ArgumentException("Number of data points must be at least the number of basis functions.");
        }

        var bases = new Func<double, double>[basisFunctions.Count];
        for (var basis = 0; basis < bases.Length; basis++)
        {
            bases[basis] = basisFunctions[basis]
                ?? throw new ArgumentException("Basis functions must not contain null entries.", nameof(basisFunctions));
        }

        var design = AllocateDesignMatrix(x.Count, bases.Length);
        for (var sample = 0; sample < x.Count; sample++)
        {
            var xValue = x[sample];
            EnsureFiniteSample(xValue, y[sample], sample);
            var offset = sample * bases.Length;
            for (var basis = 0; basis < bases.Length; basis++)
            {
                design[offset + basis] = EvaluateBasis(bases[basis], xValue);
            }
        }

        return SolveNormalEquations(design, y, x.Count, bases.Length);
    }

    /// <summary>Evaluates polynomial coefficients ordered from constant term to highest degree.</summary>
    public static double EvaluatePolynomial(IReadOnlyList<double> coefficients, double x)
    {
        ArgumentNullException.ThrowIfNull(coefficients);
        NumericGuard.Finite(x, nameof(x));

        var result = 0.0;
        for (var i = coefficients.Count - 1; i >= 0; i--)
        {
            var coefficient = coefficients[i];
            if (!double.IsFinite(coefficient))
            {
                throw new ArgumentOutOfRangeException(nameof(coefficients), "Polynomial coefficients must be finite.");
            }

            result = (result * x) + coefficient;
        }

        if (!double.IsFinite(result))
        {
            throw new ArithmeticException("Polynomial evaluation produced a non-finite value.");
        }

        return result;
    }

    private static double[] SolveNormalEquations(
        double[] design,
        IReadOnlyList<double> y,
        int sampleCount,
        int basisCount)
    {
        // Normal equations are symmetric. Accumulating only the upper triangle nearly halves
        // matrix work; we mirror it once before the linear solve.
        var upper = new double[basisCount * basisCount];
        var rhs = new double[basisCount];

        for (var sample = 0; sample < sampleCount; sample++)
        {
            var designOffset = sample * basisCount;
            var yValue = y[sample];

            for (var row = 0; row < basisCount; row++)
            {
                var rowValue = design[designOffset + row];
                var rhsContribution = yValue * rowValue;
                EnsureFiniteComputation(rhsContribution, "Least-squares normal equations produced a non-finite right-hand-side contribution.");
                var rhsUpdated = rhs[row] + rhsContribution;
                EnsureFiniteComputation(rhsUpdated, "Least-squares normal equations produced a non-finite right-hand side.");
                rhs[row] = rhsUpdated;

                var normalOffset = row * basisCount;
                for (var column = row; column < basisCount; column++)
                {
                    var contribution = rowValue * design[designOffset + column];
                    EnsureFiniteComputation(contribution, "Least-squares normal equations produced a non-finite matrix contribution.");
                    var index = normalOffset + column;
                    var updated = upper[index] + contribution;
                    EnsureFiniteComputation(updated, "Least-squares normal equations produced a non-finite matrix value.");
                    upper[index] = updated;
                }
            }
        }

        var normal = new DenseMatrix(basisCount, basisCount);
        for (var row = 0; row < basisCount; row++)
        {
            var destination = normal.GetMutableRowSpan(row);
            var upperOffset = row * basisCount;
            for (var column = row; column < basisCount; column++)
            {
                var value = upper[upperOffset + column];
                destination[column] = value;
                if (column != row)
                {
                    normal.GetMutableRowSpan(column)[row] = value;
                }
            }
        }

        return LinearSystemSolvers.SolveGaussian(normal, rhs, partialPivoting: true);
    }

    private static double[] AllocateDesignMatrix(int sampleCount, int basisCount)
    {
        var elementCount = (long)sampleCount * basisCount;
        if (elementCount > int.MaxValue)
        {
            throw new ArgumentOutOfRangeException(nameof(basisCount), "Least-squares design matrix is too large for an Int32-indexed array.");
        }

        return new double[(int)elementCount];
    }

    private static double EvaluateBasis(Func<double, double> basis, double x)
    {
        var value = basis(x);
        if (!double.IsFinite(value))
        {
            throw new ArithmeticException("A least-squares basis function returned a non-finite value.");
        }

        return value;
    }

    private static void EnsureFiniteSample(double x, double y, int sampleIndex)
    {
        if (!double.IsFinite(x) || !double.IsFinite(y))
        {
            throw new ArgumentOutOfRangeException(
                nameof(x),
                $"Least-squares sample {sampleIndex} contains a non-finite x or y value.");
        }
    }

    private static void EnsureFiniteComputation(double value, string message)
    {
        if (!double.IsFinite(value))
        {
            throw new ArithmeticException(message);
        }
    }
}
