using Sasd.Numerics.Common;
using Sasd.Numerics.LinearAlgebra;

namespace Sasd.Numerics.Approximation;

/// <summary>
/// Least-squares approximation helpers implemented with small, transparent reference algorithms.
/// </summary>
/// <remarks>
/// General linear fits use a Householder QR factorization of the design matrix. This avoids
/// explicitly forming the normal equations <c>A^T*A</c> and therefore avoids squaring the
/// condition number as the historical reference implementation did. SVD remains the planned
/// evolution for rank-deficient, underdetermined, and condition-sensitive regression workloads.
/// </remarks>
public static partial class LeastSquares
{
    /// <summary>Fits a polynomial <c>c0 + c1*x + ... + cn*x^n</c> in the least-squares sense.</summary>
    /// <remarks>
    /// Polynomial basis values are generated by recurrence (<c>1, x, x^2, ...</c>) rather than
    /// creating delegates and repeatedly calling <see cref="System.Math.Pow(double, double)"/>.
    /// The resulting design matrix is solved with Householder QR.
    /// </remarks>
    public static double[] FitPolynomial(IReadOnlyList<double> x, IReadOnlyList<double> y, int degree)
    {
        if (degree < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(degree));
        }

        NumericGuard.SameLength(x, y, nameof(x), nameof(y));
        if (x.Count == 0)
        {
            throw new ArgumentException("At least one data point is required.", nameof(x));
        }

        var basisCountLong = (long)degree + 1;
        if (basisCountLong > x.Count)
        {
            throw new ArgumentException("Number of data points must be at least degree + 1.", nameof(degree));
        }

        var basisCount = (int)basisCountLong;
        var design = new DenseMatrix(x.Count, basisCount);

        for (var sample = 0; sample < x.Count; sample++)
        {
            EnsureFiniteSample(x[sample], y[sample], sample);
            var row = design.GetMutableRowSpan(sample);
            var power = 1.0;
            for (var basis = 0; basis < basisCount; basis++)
            {
                row[basis] = power;
                if (basis + 1 < basisCount)
                {
                    power *= x[sample];
                    if (!double.IsFinite(power))
                    {
                        throw new ArithmeticException("Polynomial basis generation produced a non-finite value.");
                    }
                }
            }
        }

        return SolveQr(design, y);
    }

    /// <summary>Fits a model that is linear in the supplied basis functions.</summary>
    /// <remarks>
    /// Each basis function is evaluated exactly once for each sample and cached in a compact
    /// row-major design matrix. Besides reducing callback overhead, this gives deterministic
    /// semantics for expensive basis functions. The completed design matrix is solved by
    /// Householder QR rather than normal equations.
    /// </remarks>
    public static double[] FitBasis(
        IReadOnlyList<double> x,
        IReadOnlyList<double> y,
        IReadOnlyList<Func<double, double>> basisFunctions)
    {
        NumericGuard.SameLength(x, y, nameof(x), nameof(y));
        ArgumentNullException.ThrowIfNull(basisFunctions);
        if (x.Count == 0)
        {
            throw new ArgumentException("At least one data point is required.", nameof(x));
        }

        if (basisFunctions.Count == 0)
        {
            throw new ArgumentException("At least one basis function is required.", nameof(basisFunctions));
        }

        if (x.Count < basisFunctions.Count)
        {
            throw new ArgumentException("Number of data points must be at least the number of basis functions.");
        }

        var bases = new Func<double, double>[basisFunctions.Count];
        for (var basis = 0; basis < bases.Length; basis++)
        {
            bases[basis] = basisFunctions[basis]
                ?? throw new ArgumentException("Basis functions must not contain null entries.", nameof(basisFunctions));
        }

        var design = new DenseMatrix(x.Count, bases.Length);
        for (var sample = 0; sample < x.Count; sample++)
        {
            var xValue = x[sample];
            EnsureFiniteSample(xValue, y[sample], sample);
            var row = design.GetMutableRowSpan(sample);
            for (var basis = 0; basis < bases.Length; basis++)
            {
                row[basis] = EvaluateBasis(bases[basis], xValue);
            }
        }

        return SolveQr(design, y);
    }

    /// <summary>Evaluates polynomial coefficients ordered from constant term to highest degree.</summary>
    public static double EvaluatePolynomial(IReadOnlyList<double> coefficients, double x)
    {
        ArgumentNullException.ThrowIfNull(coefficients);
        NumericGuard.Finite(x, nameof(x));

        var result = 0.0;
        for (var i = coefficients.Count - 1; i >= 0; i--)
        {
            var coefficient = coefficients[i];
            if (!double.IsFinite(coefficient))
            {
                throw new ArgumentOutOfRangeException(nameof(coefficients), "Polynomial coefficients must be finite.");
            }

            result = (result * x) + coefficient;
        }

        if (!double.IsFinite(result))
        {
            throw new ArithmeticException("Polynomial evaluation produced a non-finite value.");
        }

        return result;
    }

    private static double[] SolveQr(DenseMatrix design, IReadOnlyList<double> y)
    {
        var factorization = QrFactorization.Decompose(design);
        return factorization.SolveLeastSquares(y);
    }

    private static double EvaluateBasis(Func<double, double> basis, double x)
    {
        var value = basis(x);
        if (!double.IsFinite(value))
        {
            throw new ArithmeticException("A least-squares basis function returned a non-finite value.");
        }

        return value;
    }

    private static void EnsureFiniteSample(double x, double y, int sampleIndex)
    {
        if (!double.IsFinite(x) || !double.IsFinite(y))
        {
            throw new ArgumentOutOfRangeException(
                nameof(x),
                $"Least-squares sample {sampleIndex} contains a non-finite x or y value.");
        }
    }
}
